=== Crgargar/LMSGI_UD4/editorial/editorial.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
  <xs:element name="editorial_aranda">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="cabecera"/>
        <xs:element ref="tabla"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="cabecera">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="titulo"/>
        <xs:element ref="contenido"/>
        <xs:element ref="descripcion"/>
        <xs:element ref="fecha_informe"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="titulo" type="xs:string"/>
  <xs:element name="contenido" type="xs:string"/>
  <xs:element name="descripcion" type="xs:string"/>
  <xs:element name="fecha_informe" type="xs:string"/>
  <xs:element name="tabla">
    <xs:complexType>
      <xs:sequence>
        <xs:element maxOccurs="unbounded" ref="region"/>
        <xs:element ref="trimestre"/>
        <xs:element ref="libros_vendidos"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="region">
    <xs:complexType>
      <xs:choice>
        <xs:element ref="centro"/>
        <xs:element ref="norte"/>
        <xs:element ref="sur"/>
      </xs:choice>
    </xs:complexType>
  </xs:element>
  <xs:element name="centro">
    <xs:complexType mixed="true">
      <xs:choice minOccurs="0" maxOccurs="unbounded">
        <xs:element ref="libro"/>
        <xs:element ref="trimestre"/>
      </xs:choice>
    </xs:complexType>
  </xs:element>
  <xs:element name="norte">
    <xs:complexType mixed="true">
      <xs:choice minOccurs="0" maxOccurs="unbounded">
        <xs:element ref="libro"/>
        <xs:element ref="trimestre"/>
      </xs:choice>
    </xs:complexType>
  </xs:element>
  <xs:element name="sur">
    <xs:complexType mixed="true">
      <xs:choice minOccurs="0" maxOccurs="unbounded">
        <xs:element ref="libro"/>
        <xs:element ref="trimestre"/>
      </xs:choice>
    </xs:complexType>
  </xs:element>
  <xs:element name="libros_vendidos" type="xs:string"/>
  <xs:element name="libro" type="xs:string"/>
  <xs:element name="trimestre" type="xs:NMTOKEN"/>
</xs:schema>

=== Crgargar/LMSGI_UD4/editorial/editorial_X.xml
<?xml version="1.0" encoding="UFT-8"?>
<editorial_aranda xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="editorial.xsd">
    <cabecera>
      <titulo>Ediciones Aranda</titulo>
      <contenido>Informe regional del ventas</contenido>
      <descripcion>Descripcion: informe de ventas para las regiones Norte, Centro y Sur</descripcion>
      <fecha_informe>30/12/2009</fecha_informe>
    </cabecera>
    <tabla>
      <region>
        <norte>norte
          <trimestre>1</trimestre>
            <libro>24000</libro>
          <trimestre>2</trimestre>
            <libro>38600</libro>
          <trimestre>3</trimestre>
            <libro></libro>
          <trimestre>4</trimestre>
            <libro></libro>
        </norte>
      </region>
      <region>
        <centro> centro
          <trimestre>1</trimestre>
            <libro></libro>
          <trimestre>2</trimestre>
            <libro>16080</libro>
          <trimestre>3</trimestre>
            <libro>25000</libro>
          <trimestre>4</trimestre>
            <libro>29000</libro>
        </centro>
      </region>
      <region>
        <sur> sur
          <trimestre>1</trimestre>
            <libro>27000</libro>
          <trimestre>2</trimestre>
            <libro>31400</libro>
          <trimestre>3</trimestre>
            <libro>40100</libro>
          <trimestre>4</trimestre>
            <libro>30000</libro>
        </sur>
      </region>
      <trimestre>Trimestre</trimestre>
      <libros_vendidos>Libros vendidos</libros_vendidos>
    </tabla>
  </editorial_aranda>
