=== Crgargar/LMSGI_UD4/modulos_cfgs/modulo.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" version="0.1" xml:lang="es">
  <xs:element name="cfgs">
    <xs:complexType>
      <xs:sequence>
        <xs:element maxOccurs="unbounded" ref="modulos"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="modulos">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="nombreModulo"/>
        <xs:element maxOccurs="unbounded" ref="UDs"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="nombreModulo" type="xs:NCName"/>
  <xs:element name="UDs">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="unidad"/>
        <xs:element ref="tema"/>
        <xs:element ref="descripcion"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="unidad" type="xs:integer"/>
  <xs:element name="tema" type="xs:string"/>
  <xs:element name="descripcion" type="xs:string"/>
</xs:schema>

=== Crgargar/LMSGI_UD4/modulos_cfgs/practicas_X.xml
<?xml version="1.0" encoding="UTF-8"?>
<cfgs xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="modulo.xsd">
    <modulos>
        <nombreModulo>Informatica</nombreModulo>
        <UDs>
            <unidad>1</unidad>
            <tema>tema 1</tema>
            <descripcion>creacion de xml</descripcion>
        </UDs>
        <UDs>
            <unidad>2</unidad>
            <tema>tema 2</tema>
            <descripcion>creacion de un DTD</descripcion>
        </UDs>
    </modulos>
    <modulos>
        <nombreModulo>Lengua</nombreModulo>
        <UDs>
            <unidad>1</unidad>
            <tema>tema 1</tema>
            <descripcion> analisis sintactico</descripcion>
        </UDs>
        <UDs>
            <unidad>2</unidad>
            <tema> tema 2</tema>
            <descripcion> lectura del libro didactico</descripcion>
        </UDs>
    </modulos>
</cfgs>
