=== Crgargar/LMSGI_UD4/clientes/clientes.dtd
<!ELEMENT sede (sede*)>
<!ELEMENT codigoSede (#PCDATA)>
<!ELEMENT nombreEmpleado (#PCDATA)>
<!ELEMENT fecha (#PCDATA)>
<!ELEMENT descripcion (#PCDATA)>
<!ELEMENT clientes (codigoCliente, numero, coste, resumen, plazo)>
<!ELEMENT codigoCliente (#PCDATA)>
<!ELEMENT numero (#PCDATA)>
<!ELEMENT coste (#PCDATA)>
<!ELEMENT resumen (#PCDATA)>
<!ELEMENT plazo (#PCDATA)>

=== Crgargar/LMSGI_UD4/clientes/clientes_So.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE clientes SYSTEM "clientes.dtd">
<clientes>
    <sede codigo="A0002">
        <nombreEmpleado>Juan</nombreEmpleado>
        <fecha>25/04/85</fecha>
        <descripcion>solvente</descripcion>
        <cliente clientesDatos="1">
            <codigoCliente>ARD-1-2-3</codigoCliente>
            <numero>2</numero>
            <coste>10.000</coste>
            <resumen>vacia</resumen>
            <plazo>3 meses</plazo>
        </cliente>
    </sede>
    <sede codigo="A0001">
        <nombreEmpleado>Ana</nombreEmpleado>
        <fecha>03/07/99</fecha>
        <descripcion>insolvente</descripcion>
        <cliente clientesDatos="2">
            <numero>1</numero>
            <coste>12.000</coste>
            <resumen>alquilada</resumen>
            <plazo>1 año</plazo>
        </cliente>
        <cliente clientesDatos="2">
            <numero>3</numero>
            <coste>10.000</coste>
            <resumen>ocupada</resumen>
            <plazo>2 año</plazo>
        </cliente>
    </sede>
</clientes>
